# Generated by Django 2.2.16 on 2022-11-12 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0016_auto_20221112_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created',), 'verbose_name': 'пост', 'verbose_name_plural': 'посты'},
        ),
    ]
